M48
; DRILL file {KiCad 7.0.10} date Tue Jan 30 21:33:04 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-30T21:33:04-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X4.8087Y-3.983
X4.8087Y-4.423
X5.18Y-3.51
X5.1881Y-2.8606
M30
